### ISSUE TITLE
Abstractification of the Graffiticode OSS project and other house cleaning

### ISSUE THREAD

**Issue by jeffdyer** [graffiticode/api#26]
I'd like us to consider refocusing the GC project around a spec and a collection of reference implementations of that spec. As part of this refactoring, I have in mind that we would keep only the specs and code that define what qualifies as GC (language syntax and semantics), APIs, and core IDE features. The goal is to enable multiple implementations of the IDE and API that are compatible with each other and the whole of the language diaspora.

To avoid obscuring the definitional and illustrative details, I suggest we move the operational bits out of the project and into forks (for example, here [https://github.com/artcompiler](https://github.com/artcompiler)). This would include all deployment scripts and packages. What would remain is what is necessary to build, run and test locally.

The initial set of repos would include:
* graffiticode-spec
* graffiticode-ide
* graffiticode-api
* graffiticode-basis
* graffiticode-L0

This proposal is in part inspired by the approach used in [https://graphql.org/](https://graphql.org/).

**Comment by jeffdyer** [comment]
@KevinDyer Let's discuss.

**Comment by KevinDyer** [comment]
I think this makes a lot of sense. I would add `graffiticode-comiler-framework` to the list of repos but I could also see that being included in `graffiticode-basis`.

Are `ide`, `api`, and `L0` reference implementation of the `spec`?

**Comment by jeffdyer** [comment]
I think compiler framework, the abstract parts, should be included in graffiticode-basis. There might be some tooling that ends up elsewhere as well. I think we'll know when we see it.

And yes. All the non-spec repos would be reference implementations (model implementations) of a compliant implementation of the spec, `graffiticode-basis` included.

**Comment by jeffdyer** [comment]
I've "forked" graffititcode, api and L0 to graffiticode-ide, graffiticode-api and graffiticode-L0 and started to strip out the operational code. We should leave the original repos with all the deploy code for now.

**Comment by KevinDyer** [comment]
ack, I'll take a look later today
